modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "druidry"
version = "${version}"
displayName = "Druidry"
authors = "Rabbitminers kurocat471 DatCoder Mimikumaster5 Eevneon"
description = '''
A broad and expansive magical & natural enchantment to Minecraft
'''
#logoFile = ""

[[dependencies.druidry]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druidry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.druidry]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"